### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kobykorman**
nullable() already sets default to null

### CODE REVIEW

**Comment by michaeldyrynda** [comment]
As far as I can tell, the `nullable` modifier only makes the field [nullable](https://github.com/illuminate/database/blob/master/Schema/Grammars/MySqlGrammar.php#L738-L743) (MySQL).

Where defined (for [MySQL](https://github.com/illuminate/database/blob/ab21e59ec5642a5f045ae0f51c91a685ea96cf4f/Schema/Grammars/MySqlGrammar.php#L738), [Posgres](https://github.com/illuminate/database/blob/ab21e59ec5642a5f045ae0f51c91a685ea96cf4f/Schema/Grammars/PostgresGrammar.php#L583), [SQLite](https://github.com/illuminate/database/blob/0d43500813aca2def4c2340d7fc1cfe7ee62c349/Schema/Grammars/SQLiteGrammar.php#L621), and [SQL Server](https://github.com/illuminate/database/blob/ab21e59ec5642a5f045ae0f51c91a685ea96cf4f/Schema/Grammars/SqlServerGrammar.php#L594)), I can't see where the `default null` is implicit - unless it is being set at the database level, in which case it's better to be explicit about your definition so as to have consistent behaviour between connections.

Is there some specific instance you've seen where using `nullable()` is sufficient and you don't also need to set `default(null)`?

**Comment by michaeldyrynda** [comment]
I can see with MySQL (MariaDB):


```sql
CREATE TABLE `testing` (
    `id` INT UNSIGNED AUTO_INCREMENT,
    `somefield` VARCHAR(255) NULL,
    `otherfield` VARCHAR(255),
    `onemorefield` VARCHAR(255) NULL DEFAULT NULL
    PRIMARY KEY (`id`)
);
```

that these are all the same, but I'm not sure this is going to have the same behaviour across different databases. I'm content to continue recommending you explicitly define the default as `null`.

**Comment by kobykorman** [comment]
Yeah, I guess you're right. I'm working with MySQL, and it's the implicit default. No idea about other databases.

See:
http://stackoverflow.com/questions/27558713/set-default-to-null-with-laravel-migration
http://stackoverflow.com/questions/25968054/null-vs-default-null-vs-null-default-null-in-mysql-column-creation

**Comment by michaeldyrynda** [comment]
I'll leave it as it is for now, as I don't use the other drivers, so don't want to inadvertently cause issues to others. Being explicit isn't going to hurt anybody :)

**Pull request closed without merging**
