### PR TITLE
Handle nullable fields with a mutator set

### PR DESCRIPTION
**Pull request by michaeldyrynda**
This PR addresses the issues raised in #9, introducing some tests to cover the case, and should resolve the issue itself

### CODE REVIEW

**Comment by mikemand** [comment]
I can see v1.2.1 tagged here on GitHub, but for some reason [Packagist](https://packagist.org/packages/iatstuti/laravel-nullable-fields) hasn't caught it yet. Any ideas why?

**Comment by michaeldyrynda** [comment]
I think it's because the build is failing in older versions of the framework. I'll fix it up and tag again in a little bit for you. My bad!

Michael Dyrynda

Sent from
https://polymail.io/

On Mon., 08 Aug. 2016 at 04:11 Micheal Mand

<
mailto:Micheal Mand notifications@github.com

> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

I can see v1.2.1 tagged here on GitHub, but for some reason
https://packagist.org/packages/iatstuti/laravel-nullable-fields
hasn't caught it yet. Any ideas why?

—

You are receiving this because you modified the open/close state.

Reply to this email directly,
https://github.com/michaeldyrynda/laravel-nullable-fields/pull/10#issuecomment-238100075
, or

**Comment by michaeldyrynda** [comment]
Hey @mikemand - I fixed this up earlier today (just 1.2.0), not sure if you'd noticed yet or not, so thought I'd ping you just to be sure. With any luck this resolves the issue for you!

**Comment by mikemand** [comment]
Thank you @michaeldyrynda!

**Comment by mikemand** [comment]
Hi @michaeldyrynda, I had a chance to test the latest version and now something weird is happening. Instead of the field being set to `NULL` if my input is empty, it is being set to the following:

```
"{\"amount\":627, \"currency\":\"USD\"}"
```

Which, without all the backslashes (and outer quotes), was what the field was set to before trying to wipe it out. My mutator is as follows:

``` php
public function setShippingAttribute($value)
{
    if ($this->attributes['charges_shipping'] == 1) {
        $currency = auth()->user()->getCurrencyFromUserCountry('USD'); // Default to USD if user's country is not set.
        $sales_tax = ['amount' => $value * 100, 'currency' => $currency];
    } else {
        $sales_tax = [];
    }

    $this->attributes['sales_tax'] = $sales_tax;
}
```

I've also tried setting `$sales_tax` to `null` if `charges_shipping` is falsey (input comes from a hidden input/checkbox combo, so values will either be 0, '0', "0", 1, '1', or "1" depending on the user's browser; more typically with double quotes but I've seen all three on Opera and MSIE).

**Comment by michaeldyrynda** [comment]
Hey @mikemand - I've spent a bit more time on this and it looks as though this isn't the package causing the error, but it's coming from Eloquent itself. If you don't `use NullableFields` in your model, you'll still get that error message. If you look at the stack trace:

```
preg_replace(): Parameter mismatch, pattern is a string while replacement is an array

/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/support/helpers.php:683
/Users/michaeld/Sites/laravel-nullablefields/vendor/illuminate/database/QueryException.php:56
/Users/michaeld/Sites/laravel-nullablefields/vendor/illuminate/database/QueryException.php:39
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Connection.php:652
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Connection.php:611
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Connection.php:391
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Connection.php:347
/Users/michaeld/Sites/laravel-nullablefields/vendor/illuminate/database/Query/Processors/Processor.php:32
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Query/Builder.php:1858
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Eloquent/Builder.php:1242
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Eloquent/Model.php:1680
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Eloquent/Model.php:1649
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Eloquent/Model.php:1540
/Users/michaeld/Sites/laravel-nullable-fields/vendor/illuminate/database/Eloquent/Model.php:570
```

This is because the mutator is fired before the check for any cast properties is run within Eloquent. You need to set your `sales_tax` attribute to a string before it's committed to the database i.e. `json_encode($sales_tax)`.

The package will then handle it appropriately.

**Comment by mikemand** [comment]
Thank you for your help @michaeldyrynda. 😃

**Pull request merged**
